# Generated by Django 4.2 on 2023-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga', models.FloatField()),
                ('harga_diskon', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='product_pics')),
                ('label', models.CharField(choices=[('Expensive', 'Diatas 20 juta'), ('Middle', 'Antara 1-20 juta'), ('Cheap', 'Dibawah 1 juta')], max_length=9)),
                ('kategori', models.CharField(choices=[('Expensive', 'Yang berhubungan dengan fashion'), ('Gadget', 'Yang berhubungan dengan gadget'), ('Food', 'Yang berhubungan dengan makanan')], max_length=9)),
            ],
        ),
    ]
