# Generated by Django 4.2.1 on 2023-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_product_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
