# Generated by Django 4.2.1 on 2023-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tahun',
            field=models.IntegerField(null=True),
        ),
    ]
