# Generated by Django 4.2 on 2023-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('NV', 'Novel'), ('CM', 'Comic'), ('MG', 'Magazine'), ('EC', 'Encyclopedia')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('NEW', 'primary'), ('SALE', 'danger'), ('BEST', 'info')], max_length=4, null=True),
        ),
    ]
