# Generated by Django 4.2 on 2023-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_digital_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('BEST', 'BEST')], max_length=4, null=True),
        ),
    ]
