# Generated by Django 4.2 on 2023-06-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('NEW', 'info'), ('SALE', 'danger'), ('BEST', 'primary')], max_length=4, null=True),
        ),
    ]
